### ISSUE TITLE
slogin

### ISSUE THREAD

**Issue by IM02** [DeathDefying/scriptss#1]
[21:34:19.510] [mods] ERROR: Please contact the module's author: https://discord.gg/659YbNY
[21:34:19.511] Error: [dispatch] [warrior-macro-master] hook: unmapped packet "sLogin"
    at Dispatch.createHook (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:236:23)
    at Dispatch.hook (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at new macroWarrior (C:\TeraToolbox\mods\warrior-macro-master\index.js:123:11)
    at ModuleManager.load (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)
    at Socket.<anonymous> (C:\TeraToolbox\bin\connectionManager.js:55:47)
    at Socket.emit (events.js:205:15)

**Comment by DeathDefying** [comment]
you realize this is not even my mod right

**Comment by IM02** [comment]
I just troll around I don't even play anymore
